# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-07 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('study_type', models.CharField(choices=[('master', 'master'), ('licence', 'licenta')], max_length=10)),
                ('faculty', models.CharField(blank=True, max_length=250)),
                ('specialization', models.CharField(blank=True, max_length=250)),
                ('year_of_study', models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV')], max_length=10)),
                ('motivation', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
