# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-11 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0003_applicationenrollment_is_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationenrollment',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='applicationenrollment',
            name='status',
            field=models.CharField(choices=[('0', 'wait'), ('1', 'rejected')], default='0', max_length=10),
        ),
    ]
