# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-14 09:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0004_auto_20180514_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 14, 9, 10, 16, 965044, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
