# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-11 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0004_auto_20180511_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationenrollment',
            name='date_applied',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
