# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-14 14:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0005_auto_20180514_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 14, 14, 39, 14, 332918, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
