# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-15 06:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0006_auto_20180514_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar/original.jpg', upload_to='avatar/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 15, 6, 20, 3, 958680, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
