# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-15 07:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0008_auto_20180515_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationenrollment',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationenrollment',
            name='country',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='applicationenrollment',
            name='county',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationenrollment',
            name='nationality',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='applicationenrollment',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='applicationenrollment',
            name='faculty',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='applicationenrollment',
            name='motivation',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='applicationenrollment',
            name='specialization',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 15, 7, 41, 51, 222798, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
