# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-18 07:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0009_auto_20180515_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationenrollment',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/original.jpg', upload_to='avatar/'),
        ),
        migrations.AlterField(
            model_name='applicationenrollment',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 18, 7, 27, 44, 217332, tzinfo=utc), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
